### PR TITLE
Remove pytest-runner

### PR DESCRIPTION
**Pull request by fabaff**
Looks like boilerplate code and is problematic for distribution packages.

### CODE REVIEW

**Comment by csernazs** [comment]
Could you please share a bit more detail about why is it causing issue for you?

I'm ok with removing this requirement, this was added to make "setup.py test" work but I think nobody is using it, but I would like to understand the background.

**Comment by fabaff** [comment]
The `setup.py` file is parsed at one time or another in most cases if one want to build a packages for a distribution. This is done to make sure that the requirements are fulfilled. E. g. for NixOS this means that `pytest-runner` needs to be pulled in even if it's not used. For the Fedora RPM packages I'm bypassing it by not using the automatic features to get the build dependencies.

`pytest-runner` show a [deprecation notice](https://github.com/pytest-dev/pytest-runner/blob/master/README.rst#deprecation-notice) for 1.5 years now. The `pip` issues don't affect distributions but regular users.

**Comment by csernazs** [comment]
Thanks for the clarification! I guess you will need a release of the master. I can do it later today.

**Comment by csernazs** [comment]
FYI: version 0.3.7 released

**Pull request merged**
