### PR TITLE
remove redundant commands from Makefile

### PR DESCRIPTION
**Pull request by beliaev-maksim**

### CODE REVIEW

**Comment by csernazs** [comment]
The purpose of `.venv/.st-venv-completed` file is to ensure that no further installs will be run once the venv is completed. This is to avoid running poetry every time when the developer runs a target which requires the venv, assuming that there are no changes in poetry.lock or pyproject.toml (if these are changed, the clean target can be used to remove the `.venv` - we can introduce a new target to remove the stamp file only if that's an issue).

While your PR simplifies the Makefile, this also ignores the presence of this stamp file and I would like to keep it to avoid extra poetry runs.

**Comment by beliaev-maksim** [comment]
@csernazs 
are you sure that such behavior cannot lead to some potential issues with not updated environment?
since it is not trivial that you need to run `make clean`

for me poetry run takes less than a second, because all deps are already installed

**Comment by csernazs** [comment]
for this issue, we could specify poetry.lock and pyprojecct.toml to makefile, like this:
`.venv/.st-venv-completed: poetry.lock pyproject.toml`

So it would compare the mtimes of it, and run poetry if the lock file or the toml file are newer than the stamp file.s are updated).

What do you think about this?

**Comment by beliaev-maksim** [comment]
@csernazs 
that would make more sense to me!
I am going to close this PR then.

**Pull request merged**
