### PR TITLE
Release version 1.0.6

### PR DESCRIPTION
**Pull request by csernazs**
- release_notes: add release note about the blocking httpserver
- Version bump to 1.0.6
- CHANGES.rst: add release notes for 1.0.6

### CODE REVIEW

**Comment by csernazs** [comment]
@matez0 

I'm about to release the next version, 1.0.6 with your blocking httpserver implementation and my minor fixes on top of it (renamings, doc fixes, kwargs fixes; no functional changes). I have also created a howto you can access [here](https://pytest-httpserver.readthedocs.io/en/latest/howto.html#running-httpserver-in-blocking-mode).

If you want you can take a look at the commits, you can find them [here](https://github.com/csernazs/pytest-httpserver/compare/902801c82804be1097a19d411e877e2dc1cb526d...master). There are other CI-related commits which are unrelated to your code.

If you find any issue, please write it to a comment or create a new issue or open a PR for it.

Thanks,
Zsolt

**Comment by matez0** [comment]
Hi Zsolt,

I am ok with the changes. Only one thing I could not understand is that why
the default host and port constants cannot stay in the base class.

I made a comment that it is practical to check the errors after stopping
the server in a fixture. And this is needed because the dispatch can also
register assertions.
Actually one unit test is explicitly doing this, but a better place would
be where the server is stopped anyway.

Thanks,
Zoli

**Comment by csernazs** [comment]
Thanks for looking at the changes!

For the default host and port in the base class: as `**kwargs` have been removed, I had to provide some defaults for them in the derived class. And this code is not valid in python3:
```
class Base:
    FOOBAR = 123


class Subclass(Base):
    def __init__(self, foobar=FOOBAR):
        self.foobar = foobar
```

It fails with `NameError: name 'FOOBAR' is not defined`.

Also, the user can change the class attribute, this is documented [here](https://pytest-httpserver.readthedocs.io/en/latest/howto.html#class-attributes).

For check_assertions, I'll update the example and the howto, thanks.

**Comment by matez0** [comment]
Thanks for the explanation and the change.

**Pull request merged**
