### PR TITLE
Where available, use tomllib from the standard library

### PR DESCRIPTION
**Pull request by hroncok**
Fallback to tomli, which is the same project,
rather than toml which wasn't updated for a while.

### CODE REVIEW

**Comment by hroncok** [comment]
OK, no idea how to please your type checkers, I give up.

**Comment by csernazs** [comment]
hi @hroncok 

Thanks for your PR! 

If we use python 3.11 for lint and mypy, I'm totally fine with using `tomllib` only so it is not required to fall back to tomli. For CI jobs I'm fine with requiring newer python vs what the library itself requires.

If you agree, could you give it a try, please?

If still not ok or you don't want to struggle, then I can also give it a try to fix it.

Zsolt

**Comment by hroncok** [comment]
Thanks. Please give it a go. The change is motivated by EPEL and it works as is for me.

**Comment by hroncok** [comment]
Thank you!

**Comment by csernazs** [comment]
I decided to keep your try..except and I also found the issue with mypy, and the only solution is to type-ignore it. Since it is a test, it is not really an issue.

Thanks again for the PR!

**Pull request merged**
